---
env:
  node: true
extends:
  - "eslint:recommended"
  - "plugin:vue/vue3-recommended"
  - "plugin:vue/vue3-essential" # This option doesn't impose formatting rules
  # - 'plugin:vue/vue3-strongly-recommended' # This option imposes formatting rules on your code to improve readability
  - "prettier"
rules:
  # override/add rules settings here, such as:
  "no-unused-vars": "warn"
  "vue/no-unused-vars": "warn"
